title: title
languageCode: en-us
titleCaseStyle: none
capitalizeListTitles: false
pluralizeListTitles: false
enableGitInfo: true
pygmentsUseClasses: true
disableHugoGeneratorInject: true

date:
  locale: ko_KR

buildFuture: true

uglyURLs: false
canonifyURLs: true

markup:
  goldmark:
    renderer:
      unsafe: true

  highlight:
    guessSyntax: true
    lineNumbersInTable: false
    tabWidth: 4

menu:
  main:
    - identifier: about
      name: about
      url: /about
      weight: 1

    - identifier: works
      name: works
      url: /works
      weight: 2
