backend:
  name: github
  repo: hippoyawn/hugo_with_cms
  branch: main
  base_url: https://sveltia-cms-auth.youngjo.workers.dev

# backend:
#   name: test-repo

logo:
  src: /assets/logo.jpg
  show_in_header: true

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 80
          width: 1920
          height: 1920
        svg:
          optimize: true

collections:
  - name: posts # Used in routes, e.g., /admin/collections/post
    label: Posts # Used in the UI
    folder: /content/posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields:
      - name: title
        label: Title

      - name: date
        label: Publish Date
        widget: datetime

      - name: image
        label: Media Files
        widget: file
        require: false

      - name: body
        label: Body
        widget: richtext
        modes: [rich_text, raw]
