backend:
  name: github
  repo: hippoyawn/hugo_with_cms
  branch: main
  base_url: https://sveltia-cms-auth.youngjo.workers.dev

# backend:
#   name: test-repo

logo:
  src: /assets/logo.jpg
  show_in_header: true

media_folder: /static/assets
public_folder: /assets

media_libraries:
  default:
    config:
      transformations:
        raster_image:
          format: webp
          quality: 80
          width: 1920
          height: 1920
        svg:
          optimize: true

collections:
  - name: works # Used in routes, e.g., /admin/collections/post
    label: Works # Used in the UI
    folder: /content/works # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    media_folder: "{{media_folder}}/works/{{slug}}"
    public_folder: "{{public_folder}}/works/{{slug}}"
    fields:
      - name: title
        label: 제목

      - name: date
        label: 날짜
        widget: datetime

      - name: medium
        label: 제작방식 및 재료

      - name: dimensions
        label: 크기
        require: false

      - name: pages
        label: 페이지 수
        widget: number
        require: false

      - name: image
        label: 이미지
        widget: file
        multiple: true
        require: false

      - name: description
        label: 설명
        widget: richtext
        modes: [rich_text, raw]
